In [84]:
import numpy as np
import pandas as pd 
#import matplotlib.pyplot as plt
#import seaborn as sns

In [85]:
df=pd.read_csv("G:\debdas/mail_data.csv")

In [86]:
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [87]:
category=pd.get_dummies(df['Category'])

In [88]:
new=pd.concat((df,category),axis=1)

In [89]:
new

Category                                            Message  ham  spam
0         ham  Go until jurong point, crazy.. Available only ...    1     0
1         ham                      Ok lar... Joking wif u oni...    1     0
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...    0     1
3         ham  U dun say so early hor... U c already then say...    1     0
4         ham  Nah I don't think he goes to usf, he lives aro...    1     0
...       ...                                                ...  ...   ...
5567     spam  This is the 2nd time we have tried 2 contact u...    0     1
5568      ham               Will ü b going to esplanade fr home?    1     0
5569      ham  Pity, * was in mood for that. So...any other s...    1     0
5570      ham  The guy did some bitching but I acted like i'd...    1     0
5571      ham                         Rofl. Its true to its name    1     0

[5572 rows x 4 columns]

In [90]:
new_data=new.drop(['Category'],axis=1)

In [91]:
new_data

Message  ham  spam
0     Go until jurong point, crazy.. Available only ...    1     0
1                         Ok lar... Joking wif u oni...    1     0
2     Free entry in 2 a wkly comp to win FA Cup fina...    0     1
3     U dun say so early hor... U c already then say...    1     0
4     Nah I don't think he goes to usf, he lives aro...    1     0
...                                                 ...  ...   ...
5567  This is the 2nd time we have tried 2 contact u...    0     1
5568               Will ü b going to esplanade fr home?    1     0
5569  Pity, * was in mood for that. So...any other s...    1     0
5570  The guy did some bitching but I acted like i'd...    1     0
5571                         Rofl. Its true to its name    1     0

[5572 rows x 3 columns]

In [92]:
new_data.isnull().sum()

Message    0
ham        0
spam       0
dtype: int64

# separate x and y

In [93]:
x=new_data.Message

In [94]:
x

0       Go until jurong point, crazy.. Available only ...
1                           Ok lar... Joking wif u oni...
2       Free entry in 2 a wkly comp to win FA Cup fina...
3       U dun say so early hor... U c already then say...
4       Nah I don't think he goes to usf, he lives aro...
                              ...                        
5567    This is the 2nd time we have tried 2 contact u...
5568                 Will ü b going to esplanade fr home?
5569    Pity, * was in mood for that. So...any other s...
5570    The guy did some bitching but I acted like i'd...
5571                           Rofl. Its true to its name
Name: Message, Length: 5572, dtype: object

In [95]:
y=new_data.spam

In [96]:
y

0       0
1       0
2       1
3       0
4       0
       ..
5567    1
5568    0
5569    0
5570    0
5571    0
Name: spam, Length: 5572, dtype: uint8

# split data set

In [97]:
from sklearn.model_selection import train_test_split

In [98]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.3)

# data preprocessing

In [99]:
from sklearn.feature_extraction.text import CountVectorizer

In [100]:
cv=CountVectorizer()

In [101]:
x_train=cv.fit_transform(xtrain)

In [102]:
x_train.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

# ML algorithm

In [103]:
from sklearn.naive_bayes import MultinomialNB

In [104]:
model=MultinomialNB()

In [105]:
model.fit(x_train,ytrain)

MultinomialNB()

In [106]:
x_test=cv.transform(xtest)

In [107]:
x_test.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [108]:
model.score(x_test,ytest)

0.9868421052631579

# check spam mail

In [109]:
new_mail=['how are you','huge offer','10% discount']

In [110]:
mail=cv.transform(new_mail)

In [111]:
mail.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [112]:
model.predict(mail)

array([0, 1, 1], dtype=uint8)